### ISSUE TITLE
Не верно работает сортировка 

### ISSUE THREAD

**Issue by axce1** [s9gf4ult/track-deal#20]
во вкладке позиции не верно отображается сортировка данных

_скрины вставлять нельзя, значит так буду рисовать_

(0.05)
0.05
(0.13)
0.23
(0.24)
0.45

очевидимо, что 0.05 и 0.23 больше чем (0.13) и (0.24)

**Comment by s9gf4ult** [comment]
Так и задумано, сортирует по модулю

**Comment by axce1** [comment]
хреновая задумака, имхо
