### ISSUE TITLE
удобный ввод стоков во время добавления сделки

### ISSUE THREAD

**Issue by s9gf4ult** [s9gf4ult/track-deal#24]
В редакторе сделки сделать:
1. Сделать ComboBox с Entry для ввода названия стока вручную с Autocompletion
2. Приляпать рядом кнопку для быстрого вызова редактора инструментов

**Comment by axce1** [comment]
ты таки осознал что не очень удобно реализован ввод стоков?

**Comment by s9gf4ult** [comment]
Я таки осознал что важно делать это быстро, Изя

**Comment by axce1** [comment]
Вы таки как никто другой меня понимаете, Сара )))
